cmake_minimum_required(VERSION 4.1.2)

if(NOT DEFINED GLOBAL_PROJECT_NAME)
    set(GLOBAL_PROJECT_NAME "error_to_load")
endif()
if(NOT DEFINED GLOBAL_PROJECT_VERSION)
    set(GLOBAL_PROJECT_VERSION "0.0.0")
endif()
if(NOT DEFINED GLOBAL_PROJECT_DESCRIPTION)
    if(DEFINED ENV{GLOBAL_PROJECT_DESCRIPTION})
        set(GLOBAL_PROJECT_DESCRIPTION "$ENV{GLOBAL_PROJECT_DESCRIPTION}")
    else()
        set(GLOBAL_PROJECT_DESCRIPTION "It was failed to load.")
    endif()
endif()
if(NOT DEFINED GLOBAL_PROJECT_HOMEPAGE)
    set(GLOBAL_PROJECT_HOMEPAGE "https://example.com")
endif()

project(${GLOBAL_PROJECT_NAME}
    LANGUAGES CXX
    VERSION ${GLOBAL_PROJECT_VERSION}
    HOMEPAGE_URL ${GLOBAL_PROJECT_HOMEPAGE}
)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Qt6 REQUIRED COMPONENTS Quick)
find_package(KF6CoreAddons)

add_subdirectory(src)
